# Generated by Django 3.1 on 2020-08-22 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling_interview', '0002_auto_20200822_1945'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interviewcreation',
            name='id',
        ),
        migrations.AlterField(
            model_name='interviewcreation',
            name='interview_id',
            field=models.CharField(default='', max_length=20, primary_key=True, serialize=False),
        ),
    ]
