# Generated by Django 3.1 on 2020-08-22 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewCreation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interview_id', models.CharField(default='', max_length=20)),
                ('email', models.EmailField(default='', max_length=254)),
                ('participation', models.CharField(default='', max_length=20)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='InterviewDetail',
            fields=[
                ('interview_id', models.CharField(default='', max_length=20, primary_key=True, serialize=False)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='User_Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=20)),
                ('email', models.EmailField(default='', max_length=254)),
                ('phone', models.IntegerField(default=0)),
                ('address', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Interviewer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default='', max_length=254)),
                ('participation', models.CharField(default='', max_length=20)),
                ('interview_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduling_interview.interviewdetail')),
            ],
        ),
        migrations.CreateModel(
            name='Interviewee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default='', max_length=254)),
                ('participation', models.CharField(default='', max_length=20)),
                ('interview_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduling_interview.interviewdetail')),
            ],
        ),
    ]
